### ISSUE TITLE
Amazing Tool & Feedback for nested scripts

### ISSUE THREAD

**Issue by princestha** [gonuit/rps#10]
I had been looking for something like this. Currently, I am using npm, but I just found this tool and I will be making my switch right now. Thank you for sharing this.

I do have feedback and would love to know what you think about this:

My Scenario

```
  build:
    $script: echo "Building Both IOS and Android APPS"
    ios: "Building just IOS"
    android: "Building just ANDROID"
```

With the above config, I would like to sometimes just run ```rps build``` and other times I would like to run ```rps build ios```
Is something like this possible?

As of today, I could potentially just do something like this, which would be very much like the npm scripts. but was just wondering if there is a way to nest as well.

```
  build: echo "Building Android and IOS"
  build:ios: echo "Building IOS"
  build:android: echo "Building Android"
```

Thank you
