### ISSUE TITLE
Multi line script only running first line

### ISSUE THREAD

**Issue by jibbers42** [gonuit/rps#16]
Hi, multi line script do not seem to be working unless I misunderstand how set them up...

```yaml
scripts:
  prepare: |
    echo 0
    echo 1
```

```
> rps prepare
> prepare
$ echo 0
echo 1
echo 2


0

```

rps version 0.7.0

Also, commands `--version` and `-v` would be convenient when reporting issues.
