### ISSUE TITLE
Missing script error

### ISSUE THREAD

**Issue by jibbers42** [gonuit/rps#2]
The readme shows script labels intended after `run:`

```yaml
scripts:
   # run is a default script. To use it, simply type
   # in the command line: "rps" - that's all!
   run: "flutter run -t lib/main_development.dart --flavor development"
      # you can define more commands like this: "rps gen"
      gen: "flutter pub run build_runner watch --delete-conflicting-outputs"
```
but this results in a missing script error.

Being not super familiar with yaml syntax I didn't see the problem and couldn't figure it out until I noticed in this project's pubspec.yaml, the `test:` label is not indented beyond `run:`.
