### ISSUE TITLE
Issues with `flutter_test` from SDK. 

### ISSUE THREAD

**Issue by jlambright** [gonuit/rps#26]
``` shell
Because every version of flutter_test from sdk depends on meta 1.15.0 and rps >=0.9.0 depends on meta ^1.16.0, flutter_test from sdk is incompatible with rps >=0.9.0.
```

_**pubspec.yaml snippet**_
``` yaml
environment: 
  sdk: ^3.6.0
  flutter: ^3.27.1
  ```
  
  I'm trying to determine how to resolve this issue, as it's not clear to me why the most recent release of rps is ahead of the Flutter master channel sdk.
