### ISSUE TITLE
Defined command cannot be run using rps

### ISSUE THREAD

**Issue by gwijaya94** [gonuit/rps#27]
Previously thankyou @gonuit, for solving issue #20 on Windows 11.
Just tried the update and I notice the script that defined on rps.yaml not running at all.
For example i tried check flutter version using rps, and it shows nothing, seems like it only print out the command.

Flutter version:
```
Flutter 3.24.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision dec2ee5c1f (8 weeks ago) • 2024-11-13 11:13:06 -0800
Engine • revision a18df97ca5
Tools • Dart 3.5.4 • DevTools 2.37.3
```

RPS version:
```
📝 rps version: 0.9.1
```

script on rps.yaml
```
scripts:
  check-version: flutter --version
  build-android: flutter build apk --release --flavor=${0}
  build:
    android:
      $before: echo "Before script"
      $script: flutter build apk --release --flavor=${0}
      $after: echo "After Script"
```

Preview running rps script:
<img width="300" alt="image" src="https://github.com/user-attachments/assets/ea476b9c-f71c-4633-9a97-532adb6728b1" />
<img width="300" alt="image" src="https://github.com/user-attachments/assets/61cb080f-8e8b-4ca5-adc7-5edb71b70084" />
