### ISSUE TITLE
Terminal keeps busy after running command

### ISSUE THREAD

**Issue by sezer** [gonuit/rps#5]
Hello, thanks for the great idea and package. I'm trying to run the rps command on the Macbook M1 machine.  Commands run successfully but the terminal keeps showing a result message. I'm not able to run a new command without ctrl+c.

```
scripts:
   # run is a default script. To use it, simply type
   # in the command line: "rps" - that's all!
   run: "flutter run -t lib/main.dart --flavor development"
   # you can define more commands like this: "rps gen"
   gen: "flutter pub run build_runner watch --delete-conflicting-outputs"
   build:
      android:
         apk-dev: "flutter build apk --dart-define FLAVOR=\"development\""
      ios:
         ipa-dev: "flutter build ipa --export-method ad-hoc --dart-define FLAVOR=\"development\""
```

I'm running **rps gen** 

```
❯ rps gen
> gen
$ flutter pub run build_runner watch --delete-conflicting-outputs
```

And then the terminal keeps stuck as below

<img width="521" alt="Screen Shot 2022-07-20 at 13 26 31" src="https://user-images.githubusercontent.com/1110304/179960255-183c5917-a258-4d51-ba9d-2937da9a1281.png">

This works as expected
```
> flutter pub run build_runner build --delete-conflicting-outputs
```
